project:
  type: website
  output-dir: docs

website:
  title: "Michael Stutzman's Data Science Blogs"
  description: "A showcase of my data science projects and learning journey"
  
  navbar:
    background: primary
    left:
      - text: "Data EDA Blog"
        href: index.md
      - text: "Data Acquisition"
        href: data_acquisition.md

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
